name: CI/CD Pipeline 

on:
  push:
    branches:
      - unitarias

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: |
          npm run cover

        env:
          HOST: ${{ secrets.HOST }}
          DATABASE: ${{ secrets.DATABASE }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}

  trigger-next-workflow:
    needs: test
    if: success()
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Next Workflow
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'workflow_id_of_the_next_workflow',  # Reemplazar con el ID real
            });
            console.log(data);

    
