name: CI/CD Pipeline 2

on:
  push:
    branches:
      - unitarias

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: |
          npm run cover

        env:
          HOST: ${{ secrets.HOST }}
          DATABASE: ${{ secrets.DATABASE }}
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}

  create-pull-request:
    needs: test
    if: success()
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: unitarias
          title: 'Merge successful unitarias tests'
          body: 'This pull request is automatically created after successful tests in unitarias.'
          labels: 'automerge'

      - name: Pull Request Number
        run: echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
  
