name: Next Workflow

on:
  workflow_run:
    workflows:
      - "CI/CD Pipeline"  # Nombre del primer flujo de trabajo
    types:
      - completed

jobs:
  next-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Realizar el merge con la rama main
      - name: Merge into Main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout main
          git merge ${{ github.event.workflow_run.head_commit.id }}
          git push origin main

      # Ejecutar las acciones adicionales que deseas realizar después del merge
      - name: Run Additional Actions
        run: |
          echo "Additional actions after successful merge"

